# Generated by Django 6.0.2 on 2026-02-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(db_index=True, max_length=200)),
                ('name_official', models.CharField(max_length=200)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('capital', models.CharField(blank=True, max_length=200)),
                ('subregion', models.CharField(blank=True, max_length=100)),
                ('population', models.BigIntegerField(default=0)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('flag_svg', models.URLField(blank=True, max_length=500)),
                ('flag_png', models.URLField(blank=True, max_length=500)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('coat_of_arms_svg', models.URLField(blank=True, max_length=500)),
                ('coat_of_arms_png', models.URLField(blank=True, max_length=500)),
                ('currencies', models.JSONField(blank=True, default=dict)),
                ('languages', models.JSONField(blank=True, default=dict)),
                ('timezones', models.JSONField(blank=True, default=list)),
                ('continents', models.JSONField(blank=True, default=list)),
                ('borders', models.JSONField(blank=True, default=list)),
                ('independent', models.BooleanField(default=True)),
                ('un_member', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name_common'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlagCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('territory', 'Territory'), ('historical', 'Historical'), ('state', 'State/Province'), ('international', 'International Organization'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('flag_image', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_flags', to='app.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='app.region'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name_common'], name='app_country_name_co_989823_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['region'], name='app_country_region__93b378_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['population'], name='app_country_populat_5bd40a_idx'),
        ),
    ]
