# Generated by Django 6.0.2 on 2026-02-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcollection',
            name='wikidata_id',
            field=models.CharField(blank=True, db_index=True, help_text='Wikidata QID for deduplication', max_length=20),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='category',
            field=models.CharField(choices=[('territory', 'Territory'), ('historical', 'Historical'), ('state', 'State/Province'), ('city', 'City / Municipality'), ('international', 'International Organization'), ('region', 'Region / Subdivision'), ('other', 'Other')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='flagcollection',
            index=models.Index(fields=['category'], name='app_flagcol_categor_1243aa_idx'),
        ),
    ]
