# Generated by Django 6.0.5 on 2026-05-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cca3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('name_common', models.CharField(max_length=150)),
                ('name_official', models.CharField(max_length=200)),
                ('capital', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100)),
                ('population', models.BigIntegerField()),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('flag_svg', models.URLField(max_length=500)),
                ('flag_png', models.URLField(max_length=500)),
                ('coat_of_arms_svg', models.URLField(blank=True, max_length=500)),
                ('is_independent', models.BooleanField(default=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CountryFlag',
        ),
    ]
