# Generated by Django 6.0.2 on 2026-03-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_flagcollection_wikidata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.CharField(choices=[('sovereign', 'Sovereign State'), ('territory', 'Territory'), ('historical', 'Historical'), ('other', 'Other')], db_index=True, default='sovereign', max_length=20),
        ),
    ]
