# Generated by Django 6.0.5 on 2026-06-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_country_delete_countryflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='coat_of_arms_svg',
        ),
    ]
