# Generated by Django 6.0.2 on 2026-03-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_country_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagcollection',
            name='description',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
