# Generated by Django 6.0.5 on 2026-06-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_country_coat_of_arms_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='entity_type',
            field=models.CharField(choices=[('SOVEREIGN', 'Suverénní stát'), ('DEPENDENT', 'Závislé území'), ('DISPUTED', 'Sporné území'), ('ANTARCTIC', 'Antarktida')], default='SOVEREIGN', max_length=20),
        ),
    ]
