# Generated by Django 6.0.3 on 2026-03-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_nickname_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname_change_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
