# Generated by Django 6.0.3 on 2026-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_last_nickname_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagcollection',
            name='wikidata_id',
            field=models.CharField(blank=True, help_text='Wikidata QID for deduplication', max_length=20, null=True, unique=True),
        ),
    ]
