# Generated by Django 6.0.3 on 2026-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_flagcollection_wikidata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcollection',
            name='image_file',
            field=models.FileField(blank=True, help_text='Local copy of the flag image', null=True, upload_to='flags/'),
        ),
    ]
