# Generated by Django 6.0.3 on 2026-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_flagcollection_slug_alter_country_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagcollection',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
