# Generated by Django 6.0.3 on 2026-03-18 18:09

from django.db import migrations, models
from django.utils.text import slugify


def backfill_unique_slugs(apps, schema_editor):
    FlagCollection = apps.get_model('app', 'FlagCollection')

    used = set()

    def normalize_base(value, fallback, max_len=255):
        base = slugify(value) if value else ''
        if not base:
            base = slugify(fallback) if fallback else ''
        if not base:
            base = 'flag'
        return base[:max_len]

    def make_unique(base, pk):
        if base not in used:
            used.add(base)
            return base

        suffix = f"-{pk}"
        trimmed = base[: 255 - len(suffix)]
        candidate = f"{trimmed}{suffix}"
        counter = 2
        while candidate in used:
            extra = f"-{pk}-{counter}"
            trimmed = base[: 255 - len(extra)]
            candidate = f"{trimmed}{extra}"
            counter += 1

        used.add(candidate)
        return candidate

    for obj in FlagCollection.objects.order_by('id').only('id', 'name', 'slug'):
        current = (obj.slug or '').strip()
        base = normalize_base(current, obj.name)
        final_slug = make_unique(base, obj.id)

        if current != final_slug:
            obj.slug = final_slug
            obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_flagcollection_slug_alter_country_id_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_unique_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='flagcollection',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
