# Generated by Django 5.2.12 on 2026-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_flagcollection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcollection',
            name='area_km2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flagcollection',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flagcollection',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flagcollection',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
