# Generated by Django 5.2.12 on 2026-03-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_flagcollection_area_km2_flagcollection_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcollection',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visible on the website'),
        ),
        migrations.AddField(
            model_name='flagcollection',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Checked by human or AI'),
        ),
    ]
