# Generated by Django 5.2.12 on 2026-04-03 18:58

from django.db import migrations, models


def normalize_legacy_flag_categories(apps, schema_editor):
    FlagCollection = apps.get_model('app', 'FlagCollection')
    allowed = {'state', 'territory', 'city', 'region', 'historical', 'international'}

    FlagCollection.objects.filter(category='other').update(category='region')
    FlagCollection.objects.exclude(category__in=allowed).update(category='historical')


def reverse_normalize_legacy_flag_categories(apps, schema_editor):
    # Irreversible with certainty: keep normalized values on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_flagcollection_is_public_flagcollection_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcollection',
            name='name_cs',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (Czech)'),
        ),
        migrations.AddField(
            model_name='flagcollection',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (German)'),
        ),
        migrations.RunPython(
            normalize_legacy_flag_categories,
            reverse_normalize_legacy_flag_categories,
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='category',
            field=models.CharField(choices=[('state', 'State'), ('territory', 'Territory'), ('city', 'City / Municipality'), ('region', 'Region / Subdivision'), ('historical', 'Historical'), ('international', 'International Organization')], max_length=100, verbose_name='Category'),
        ),
        migrations.AddConstraint(
            model_name='flagcollection',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ('state', 'territory', 'city', 'region', 'historical', 'international'))), name='flagcollection_category_valid'),
        ),
    ]
