# Generated by Django 5.2.12 on 2026-04-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_country_options_alter_flagcollection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name_common'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='flagcollection',
            options={'ordering': ['name'], 'verbose_name': 'Flag Collection', 'verbose_name_plural': 'Flag Collections'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='country',
            name='borders',
            field=models.JSONField(blank=True, default=list, verbose_name='Borders'),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=200, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cca2',
            field=models.CharField(max_length=2, unique=True, verbose_name='ISO Alpha-2'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cca3',
            field=models.CharField(max_length=3, unique=True, verbose_name='ISO Alpha-3'),
        ),
        migrations.AlterField(
            model_name='country',
            name='coat_of_arms_png',
            field=models.URLField(blank=True, max_length=500, verbose_name='Coat of Arms PNG'),
        ),
        migrations.AlterField(
            model_name='country',
            name='coat_of_arms_svg',
            field=models.URLField(blank=True, max_length=500, verbose_name='Coat of Arms SVG'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continents',
            field=models.JSONField(blank=True, default=list, verbose_name='Continents'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currencies',
            field=models.JSONField(blank=True, default=dict, verbose_name='Currencies'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=10, verbose_name='Flag Emoji'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_png',
            field=models.URLField(blank=True, max_length=500, verbose_name='Flag PNG'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_svg',
            field=models.URLField(blank=True, max_length=500, verbose_name='Flag SVG'),
        ),
        migrations.AlterField(
            model_name='country',
            name='independent',
            field=models.BooleanField(default=True, verbose_name='Independent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.JSONField(blank=True, default=dict, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='country',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_common',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Common Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_official',
            field=models.CharField(max_length=200, verbose_name='Official Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(default=0, verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='app.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.CharField(choices=[('sovereign', 'Sovereign State'), ('territory', 'Territory'), ('historical', 'Historical'), ('other', 'Other')], db_index=True, default='sovereign', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subregion'),
        ),
        migrations.AlterField(
            model_name='country',
            name='timezones',
            field=models.JSONField(blank=True, default=list, verbose_name='Timezones'),
        ),
        migrations.AlterField(
            model_name='country',
            name='un_member',
            field=models.BooleanField(default=False, verbose_name='UN Member'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='area_km2',
            field=models.FloatField(blank=True, null=True, verbose_name='Area (km²)'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_flags', to='app.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='description',
            field=models.JSONField(blank=True, default=dict, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='flag_image',
            field=models.URLField(max_length=500, verbose_name='Flag Image URL'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='image_file',
            field=models.FileField(blank=True, help_text='Local copy of the flag image', null=True, upload_to='flags/', verbose_name='Flag Image File'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visible on the website', verbose_name='Is Public'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Checked by human or AI', verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='flagcollection',
            name='wikidata_id',
            field=models.CharField(blank=True, help_text='Wikidata QID for deduplication', max_length=20, null=True, unique=True, verbose_name='Wikidata ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_nickname_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Nickname Change'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname_change_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nickname Change Count'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
