# Generated by Django 5.2.12 on 2026-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_country_options_alter_flagcollection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagcollection',
            name='category',
            field=models.CharField(choices=[('state', 'State'), ('territory', 'Territory'), ('city', 'Obec / Město'), ('region', 'Region / Subdivision'), ('historical', 'Historical'), ('international', 'International Organization')], max_length=100, verbose_name='Category'),
        ),
    ]
