# Generated by Django 5.2.12 on 2026-04-05 16:45

from django.db import migrations, models


def migrate_category_values_forward(apps, schema_editor):
    """
    Update category values from old to new terminology:
    - 'state' -> 'country'
    - 'territory' -> 'dependency'
    """
    FlagCollection = apps.get_model('app', 'FlagCollection')
    
    # Update state -> country
    state_count = FlagCollection.objects.filter(category='state').update(category='country')
    
    # Update territory -> dependency
    territory_count = FlagCollection.objects.filter(category='territory').update(category='dependency')
    
    print(f"Data migration completed:")
    print(f"  - Updated {state_count} records from 'state' to 'country'")
    print(f"  - Updated {territory_count} records from 'territory' to 'dependency'")


def migrate_category_values_backward(apps, schema_editor):
    """
    Reverse the category migration for rollback:
    - 'country' -> 'state'
    - 'dependency' -> 'territory'
    """
    FlagCollection = apps.get_model('app', 'FlagCollection')
    
    # Reverse country -> state
    country_count = FlagCollection.objects.filter(category='country').update(category='state')
    
    # Reverse dependency -> territory
    dependency_count = FlagCollection.objects.filter(category='dependency').update(category='territory')
    
    print(f"Data migration reversed:")
    print(f"  - Updated {country_count} records from 'country' to 'state'")
    print(f"  - Updated {dependency_count} records from 'dependency' to 'territory'")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_flagcollection_category'),
    ]

    operations = [
        # Step 1: Remove the old constraint so we can update the data
        migrations.RemoveConstraint(
            model_name='flagcollection',
            name='flagcollection_category_valid',
        ),
        # Step 2: Update the data
        migrations.RunPython(migrate_category_values_forward, migrate_category_values_backward),
        # Step 3: Update the field choices
        migrations.AlterField(
            model_name='flagcollection',
            name='category',
            field=models.CharField(
                choices=[
                    ('country', 'Country'),
                    ('dependency', 'Dependency'),
                    ('city', 'Obec / Město'),
                    ('region', 'Region / Subdivision'),
                    ('historical', 'Historical'),
                    ('international', 'International Organization')
                ],
                max_length=100,
                verbose_name='Category'
            ),
        ),
        # Step 4: Add the new constraint
        migrations.AddConstraint(
            model_name='flagcollection',
            constraint=models.CheckConstraint(
                condition=models.Q(category__in=(
                    'country',
                    'dependency',
                    'city',
                    'region',
                    'historical',
                    'international'
                )),
                name='flagcollection_category_valid'
            ),
        ),
    ]
