# Generated by Django 5.2.12 on 2026-04-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_migrate_category_terminology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='area',
            new_name='area_km2',
        ),
    ]
