# Generated by Django 5.2.12 on 2026-04-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_area_country_area_km2'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flagcollection',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
