# Generated by Django 5.2.12 on 2026-04-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_country_search_name_flagcollection_search_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'sovereign'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencies', to='app.country', verbose_name='Owner Country'),
        ),
    ]
