# Generated by Django 5.2.12 on 2026-04-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_add_owner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='system_of_government',
            field=models.CharField(blank=True, help_text="Type of government system (e.g., 'Parliamentary democracy', 'Presidential republic')", max_length=200, null=True, verbose_name='System of Government'),
        ),
    ]
