# Generated by Django 5.2.12 on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_country_system_of_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagcollection',
            name='category',
            field=models.CharField(
                choices=[
                    ('country', 'Country'),
                    ('dependency', 'Dependency'),
                    ('micronation', 'Micronation'),
                    ('city', 'Obec / Město'),
                    ('region', 'Region / Subdivision'),
                    ('historical', 'Historical'),
                    ('international', 'International Organization'),
                ],
                max_length=100,
                verbose_name='Category',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='flagcollection',
            name='flagcollection_category_valid',
        ),
        migrations.AddConstraint(
            model_name='flagcollection',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    category__in=(
                        'country',
                        'dependency',
                        'micronation',
                        'city',
                        'region',
                        'historical',
                        'international',
                    )
                ),
                name='flagcollection_category_valid',
            ),
        ),
    ]
