# Generated by Django 5.2.12 on 2026-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_flagcollection_add_micronation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_cs',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (Czech)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (German)'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('independent', True), ('owner__isnull', False), _connector='OR'), name='dependency_must_have_owner'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('independent', False), ('owner__isnull', True), _connector='OR'), name='independent_country_has_no_owner'),
        ),
        migrations.AddConstraint(
            model_name='flagcollection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__in', ['country', 'dependency']), _negated=True), ('country__isnull', False), _connector='OR'), name='country_and_dependency_must_link_to_country_model'),
        ),
    ]
