# Generated by Django 5.2.12 on 2026-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_country_description_country_name_cs_country_name_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description_cs',
            field=models.TextField(blank=True, verbose_name='Description (Czech)'),
        ),
        migrations.AddField(
            model_name='country',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Description (German)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description (EN/Default)'),
        ),
    ]
