# Generated by Django 5.2.12 on 2026-04-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_country_description_cs_country_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital_cs',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Capital (Czech)'),
        ),
        migrations.AddField(
            model_name='country',
            name='capital_de',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Capital (German)'),
        ),
        migrations.AddField(
            model_name='country',
            name='region_cs',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Region (Czech)'),
        ),
        migrations.AddField(
            model_name='country',
            name='region_de',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Region (German)'),
        ),
        migrations.AddField(
            model_name='country',
            name='subregion_cs',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Subregion (Czech)'),
        ),
        migrations.AddField(
            model_name='country',
            name='subregion_de',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Subregion (German)'),
        ),
        migrations.AddField(
            model_name='country',
            name='system_of_government_cs',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='System of Government (Czech)'),
        ),
        migrations.AddField(
            model_name='country',
            name='system_of_government_de',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='System of Government (German)'),
        ),
    ]
