# Auto-generated by classify_flags_actions.py
# Mapping: wikidata_id -> decision payload

WIKIDATA_ACTION_MAP = {
  "Q100143020": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "historical",
    "name": "Infanterie-Regiment „Graf Schwerin“ (3. Pommersches) Nr. 14",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q101081": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Provence",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q1017396": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Bushmanland",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1022": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Stuttgart",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q1028095": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Cambay State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1029062": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Martyazo",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q103801": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "East Prussia",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1041310": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Nagaoka Domain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q104285": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Occitania",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q10512734": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "historical",
    "name": "Göta Artillery Regiment",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q10512744": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "historical",
    "name": "Göta Armoured Guards regiment",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q1052040": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Cayor",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1054184": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Khmer Republic",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q10542866": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "historical",
    "name": "Kalmar Regiment",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q10543875": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "historical",
    "name": "Karlskrona Grenadier Regiment",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q10547194": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "historical",
    "name": "Fixed Infantry Regiment of Havana",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q1055": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Hamburg",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q10602644": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "historical",
    "name": "Northern Scanian Regiment",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q1060551": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Tsu Domain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1061057": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Aceh Sultanate",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1062072": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Owari Domain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1062190": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Himeji Domain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1062225": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Hikone Domain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q106293025": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Riethoven",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q106327880": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Rijswijk",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q106363391": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Dussen",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q106365333": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Witmarsum",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q10671160": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "historical",
    "name": "Scanian Dragoon Regiment",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q10672505": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "historical",
    "name": "Småland Artillery Regiment",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q10672508": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "historical",
    "name": "Småland hussar regiment",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q1067713": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Ōmura Domain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1069187": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Kishū Domain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1071439": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Merina Kingdom",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1072140": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Roman Republic",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q107258515": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Pahlavi Iran",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q107380": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Lippe",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q107426": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Anjou",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1081620": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Siam",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q10828323": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "French Annam",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1085": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Praha",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q10863325": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Ōno Domain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q109653972": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Lemosin",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q11040572": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Baltic State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1106424": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Darawiish",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1122449": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Guion Line",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1126102": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.36,
    "current_category": "historical",
    "name": "Italian Social Movement - National Right",
    "reasons": [
      "junk:political"
    ]
  },
  "Q1128488": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Swains Island",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1129599": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Levente",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q11317232": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Chitral State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q11368493": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Tannan",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q11377333": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Konda",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1140943": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Kokura Domain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1142": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Alsace",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q1142049": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.36,
    "current_category": "historical",
    "name": "North West Company",
    "reasons": [
      "junk:company"
    ]
  },
  "Q1142571": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Lyonnais",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q11430686": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Tadoshi",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q114331288": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Kherson Oblast",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1166080": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Darien scheme",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q11669665": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Takashima",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q117273360": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Akal Sena",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q11781502": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "historical",
    "name": "Ministry of Military Affairs",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q1179": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Aquitaine",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q11825603": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Uman County",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q11825790": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Ushitsa County",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1182613": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Defense Commissary Agency",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q1185174": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.44,
    "current_category": "historical",
    "name": "Rhodesian Front",
    "reasons": [
      "junk:political"
    ]
  },
  "Q1185346": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Demerara",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q11888401": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Pohja Brigade",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1189704": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Tosa Domain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1206012": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "German Reich",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q12060804": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Isle de France",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1209": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Freie Hansestadt Bremen",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q12100322": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "State Treasury",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1231992": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Oltre Giuba",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q12406729": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "historical",
    "name": "Israeli Military Governorate",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q126781": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Těšínsko",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q129286": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "British Raj",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q129597": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Roskomnadzor",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q13646141": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "territory",
    "name": "Malaysian Fire and Rescue Department",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q14103": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Champagne-Ardenne",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q1457322": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Ostmark",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q146351": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Liberec",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q146597": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Zand Iran",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q146720": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Mandatory Iraq",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q146740": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Jabal Druze",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q146761": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Hatay State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q146880": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "State of Syria",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q14708404": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Cherokee Nation",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1481436": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "County of Foix",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q148689": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Niederlausitz",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q14960": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Brno",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q1506615": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Guangzhouwan",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q15180": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Soviet Union",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q15240384": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Saint Vincent",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q15240466": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "British Cyprus",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q153529": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Duchy of Milan",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q156513": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Banat Republic",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q156974": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Ústí nad Labem",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q15893836": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Road Agency",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q161062": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Togoland",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q16436471": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Agency for Mineral Resources",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q16506": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "České Budějovice",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q1663537": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Inini",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q16697652": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "State Agency of Reserves of Ukraine",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q16711297": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Agency for Scientific Organizations",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q170072": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Dutch Republic",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q17009": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Poitou-Charentes",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q170174": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Papal States",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q17018915": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "international",
    "name": "Sham Legion",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q170603": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "New Spain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q170604": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "New France",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1707": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Kiel",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q1709": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Schwerin",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q171018": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Zlín",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q1711": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Potsdam",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q1715": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Hannover",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q1718": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Düsseldorf",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q171965": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Luhansk Oblast",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q17197946": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "British Tonga",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1724": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Saarbrücken",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q172640": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "North Vietnam",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1729": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Erfurt",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q173082": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Dacia",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1758977": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Rostekhnadzor",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q179313": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Alderney",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q180139": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Hradec Králové",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q183111": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Jihlava",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q1861984": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Seberang Perai",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q189545": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Zengid dynasty",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q191582": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "international",
    "name": "COMECON",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q1937192": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "territory",
    "name": "Ministry of Defence Police",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q199821": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Gran Colombia",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q199841": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "South Yemen",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q200130": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Azad Kashmir",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q202023": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Herm",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q202780": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Peter I Island",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2042600": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Tax Police Service of the Russian Federation",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q207353": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Acadia",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q21013234": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "New Courland",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q213510": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Belgian Congo",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q213763": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Béarn",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q214102": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Union",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2145397": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Goshen",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2145402": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "South Peru",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2150951": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "State of Haiti",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q215613": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.32,
    "current_category": "international",
    "name": "Unrepresented Nations and Peoples Organization",
    "reasons": [
      "ambiguous:junk_low_confidence"
    ]
  },
  "Q217169": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Rhodesia",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2181": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Aysén Region",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q221357": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Dutch Brazil",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2221701": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Sangli State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2280": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Minsk",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q23148": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Cornwall",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2340665": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Basutoland",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q23427": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "South Ossetia",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2347909": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "East Bengal",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2365048": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Adal Sultanate",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q23681": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Northern Cyprus",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q23730961": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Puerto Carreño",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2425785": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "State Border Guard Service of Ukraine",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q2431480": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Tibetan Empire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2444884": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Tibet",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2506068": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Azadistan",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2538511": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Kenya Colony",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q25396": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Bonaire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2564694": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Powys Fadog",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2569593": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "French Canada",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q258391": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "city",
    "name": "Werden",
    "reasons": [
      "wrong_category:city->historical"
    ]
  },
  "Q258532": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "British America",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2608489": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Aztec Empire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2617267": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Ottoman Iraq",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q26180": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Sint Eustatius",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2621587": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Waqooyi-Bari",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2625535": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Foreign Intelligence Service of Ukraine",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q2640598": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Kabardia",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q267584": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Yemen Republic",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q26996": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Kidarites",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2712121": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Irish Republic",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2749": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "city",
    "name": "Augsburg",
    "reasons": [
      "wrong_category:city->historical"
    ]
  },
  "Q27899821": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Mecklenburg",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q28025": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Ryukyu Kingdom",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q28179": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Joseon",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q28208": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Goryeo",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q28233": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Korean Empire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q28307": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Mustang",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2833": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Freiburg im Breisgau",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q28370": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Goguryeo",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q284568": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Italian Libya",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q28573": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Inca Empire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q290781": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "AD Almería",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2989469": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Makran",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q2989491": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Kharan State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q30573": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Lokot Autonomy",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q30607493": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Wituland",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q30623": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Manchukuo",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q3076765": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Ottoman Syria",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q3088976": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.44,
    "current_category": "historical",
    "name": "National Movement",
    "reasons": [
      "junk:political"
    ]
  },
  "Q3108185": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Ba'athist Iraq",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q315009": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Reichsnährstand",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q3177663": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Pakualaman",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q322187": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "New Sweden",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q3246245": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "West Punjab",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q327": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Brittany",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q3279296": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Sweden-Finland",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q3284315": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Samudra Pasai",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q33946": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Czechoslovakia",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q34366": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Tasmania",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q34614186": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Schaesberg",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q34754": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Somaliland",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q35226899": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Maarheeze",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q36989": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Pardubice",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q370736": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Cape Colony",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q373988": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Beylik of Teke",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q384544": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Karlovy Vary",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q38872": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Prussia",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q39193": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Čechy",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q4044": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "city",
    "name": "Offenburg",
    "reasons": [
      "wrong_category:city->historical"
    ]
  },
  "Q426025": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Duchy of Savoy",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q431731": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Tanganyika",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q43266": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Morava",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q43296": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Wake Island",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q43453": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Plzeň",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q4353455": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Air Transport Agency",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q4370220": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Kenya Police",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q44687": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Schutzstaffel",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q4481706": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Agency for Rail Transport",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q4481711": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Agency for Maritime and River Transport",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q4481714": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Agency for State Reserves",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q4481721": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal State Border Management Agency (Russian Federation)",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q4481723": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "territory",
    "name": "Federal Agency for the supply of weapons, military, special equipment and materiel",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q4481725": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Agency for Fishery",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q4481740": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Biomedical Agency",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q45551": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "České Slezsko",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q463": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Rhône-Alpes",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q4635873": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "historical",
    "name": "37th Arkansas Infantry Regiment",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q467627": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Durrani Empire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q468814": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Dahomey",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q472146": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Lagos Colony",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q473748": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Buganda",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q48073106": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Afrin Region",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q484195": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Timurid Empire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q49910": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Colony of Aden",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q508014": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "French Sudan",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q532048": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Sandur State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q532090": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Canada Border Services Agency",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q538636": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Ankole",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q55304": {
    "actions": {
      "category": "historical",
      "is_verified": false
    },
    "confidence": 0.51,
    "current_category": "state",
    "name": "American occupation zone in Germany",
    "reasons": [
      "ambiguous:junk_low_confidence",
      "wrong_category:state->historical"
    ]
  },
  "Q55527": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "historical",
    "name": "United States Military Government of the Ryukyu Islands",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q555994": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Aq Qoyunlu",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q56036": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "West Berlin",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q568712": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Samorian state",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q5748051": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Málaga Canton",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q5803023": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Tacna",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q5815": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Tyumen",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q5831": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Melilla",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q584435": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Patani Kingdom",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q589662": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Royal Prussia",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q590743": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Ruanda-Urundi",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q591233": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Bourbonnais",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q5939": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Landkreis Grafschaft Bentheim",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q5963": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Region Hannover",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q600093": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Habsburg Spain",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q608427": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "United States Department of the Interior",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q614072": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Tlaxcala",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q6272": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Städteregion Aachen",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q627449": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Hotak dynasty",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q628807": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "United States Department of Labor",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q63158027": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Qajar Iran",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q6320215": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "National Police of Peru",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q635394": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Massina Empire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q639073": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "South Kasai",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q6392396": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Kentucky State Police",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q64": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Berlin",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q640267": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Dejima",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q649310": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Idar State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q654766": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "North Peru",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q657861": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Dholpur State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q657946": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Kolhapur State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q6681947": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Los Angeles Airport Police",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q668294": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Kamerun",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q671700": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.36,
    "current_category": "territory",
    "name": "Israel Postal Company",
    "reasons": [
      "junk:company"
    ]
  },
  "Q675322": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Berbice",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q682669": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Malo-les-Bains",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q688654": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Dubăsari",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q693911": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "Bizone",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q6974114": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.44,
    "current_category": "historical",
    "name": "National Liberation Front",
    "reasons": [
      "junk:political"
    ]
  },
  "Q706553": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "County of Nice",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q713750": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "West Germany",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q7184": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "international",
    "name": "NATO",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q7209550": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "territory",
    "name": "Police and Border Guard Board",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q72356": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Poggiomarino",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q72785": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Cretan State",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q7369930": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Federal Agency for Construction and Housing and Communal Services",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q748300": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Louisiana",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q7603095": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "State Border Guard",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q7603096": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "Lithuanian State Border Guard Service",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q7603765": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "State of Malta",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q7646305": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Surinam",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q7809": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "international",
    "name": "UNESCO",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q7892266": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.54,
    "current_category": "territory",
    "name": "United States Virgin Islands Police Department",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q7893618": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.4,
    "current_category": "historical",
    "name": "United Tribes of New Zealand",
    "reasons": [
      "junk:ethnic_human_group"
    ]
  },
  "Q789915": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "United States Department of State",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q7904317": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.72,
    "current_category": "territory",
    "name": "Kurköln",
    "reasons": [
      "wrong_category:territory->historical"
    ]
  },
  "Q7943": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Oberlausitz",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q7984443": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "West Bengal Police",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q80207925": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "historical",
    "name": "Södermanland Armored Regiment",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q81011": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Horní Slezsko",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q81137": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Olomouc",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q815524": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Belgian Empire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q8268": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "eurozone",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q83164": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.36,
    "current_category": "historical",
    "name": "East India Company",
    "reasons": [
      "junk:company"
    ]
  },
  "Q83618": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Maratha Empire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q837017": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Altbayern",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q8385": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Ostrava",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q845368": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Río Muni",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q852211": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.38,
    "current_category": "territory",
    "name": "United States Department of Transportation",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q85787955": {
    "actions": {
      "is_public": false
    },
    "confidence": 0.46,
    "current_category": "territory",
    "name": "National Police Agency",
    "reasons": [
      "junk:milgov"
    ]
  },
  "Q858887": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Pathet Lao",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q869650": {
    "actions": {
      "category": "historical"
    },
    "confidence": 0.9,
    "current_category": "state",
    "name": "Chablais",
    "reasons": [
      "wrong_category:state->historical"
    ]
  },
  "Q8733": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Qing dynasty",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q894030": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Bornu Empire",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q912382": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Danish India",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q948110": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.22,
    "current_category": "city",
    "name": "vojenský újezd Hradiště",
    "reasons": [
      "ambiguous:junk_low_confidence"
    ]
  },
  "Q949280": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Jubaland",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q950240": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.58,
    "current_category": "city",
    "name": "Freie und Hansestadt Lübeck",
    "reasons": [
      "ambiguous:category_conflict:city->state"
    ]
  },
  "Q950326": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Tongmenghui",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q957196": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "historical",
    "name": "Sagallo",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  },
  "Q957891": {
    "actions": {
      "is_verified": false
    },
    "confidence": 0.3,
    "current_category": "territory",
    "name": "EPRON",
    "reasons": [
      "ambiguous:insufficient_metadata"
    ]
  }
}
